# Pretzel Settings
pretzel:
    engine: liquid

# Site Setup
title:            AnonJr.com
tagline:          '[Insert witty by-line here]'
description:      'The personal blog of AnonJr'
imageurl:         '/res/gravatar.png'
url:              //blog.anonjr.com
only_frontmatter_categories: true

author:
  name:           'Mark Bussell Jr. (AnonJr)'
  url:            https://twitter.com/anonjr

# Site Config
tag_pages_layout: tagpage
show_drafts:      false

# Disqus - anonjr.disqus.com
disqus_short_name: anonjr
disqus_show_comment_count: true

# Google Analytics
google_analytics_tracking_id: UA-42177830-2

# Permalinks
permalink:        /:year/:month/:title.html
paginate_path:    "page/:num"

paginate:         5

# Compress Layout settings
compress_html:
  clippings: all
  blanklines: true

# Misc
exclude:
  - _misc
  - _pretzel
  - deploy.cmd
  - test.cmd
  - readme.md
  - .gitignore
  - .git
  - docs