# Build settings
markdown: kramdown
liquid:
  error_mode: strict
sass:
    style: compressed

# Site Setup
locale:           "en"
timezone:         America/New_York
title:            AnonJr.com
tagline:          '[Insert witty by-line here]'
description:      'The personal blog of AnonJr'
imageurl:         '/res/gravatar.png'
url:              https://www.anonjr.com
only_frontmatter_categories: true

author:
  name:           'Mark Bussell Jr. (AnonJr)'
  url:            https://twitter.com/anonjr

# Site Config
show_drafts: false
future: false
excerpt_separator: <!--more-->

# Collections
collections:
  pages:
    output: true
    permalink: /p/:title:output_ext
  styleguide:
    output: true

defaults:
  # Posts defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comments: false
      author: AnonJr
  # Pages defaults
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: page

# Disqus - anonjr.disqus.com
disqus_enable: false
disqus_short_name: #anonjr
disqus_show_comment_count: #true

# SEO Related
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

# Social Sharing
twitter:
  username               : "@AnonJr"
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 : "/res/favicon-152x152.png" # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : Person # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles

# Google Analytics
google_analytics_tracking_id: UA-42177830-2

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page/:num.html
permalink: /:year/:month/:title.html

# Search
search_full_content: false # can have performance implications for large sites

tag_archive_path: "/tag/:name"
# https://github.com/jekyll/jekyll-archives
jekyll-archives:
  enabled:
    - tags
  layouts:
    tag: tagpage
  permalinks:
    tag: /tag/:name/

# HTML Compression
# - http://jch.penibelst.de/
#compress_html:
#  clippings: all
#  blanklines: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - readme.md
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - .git
  - node_modules
  - misc/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-archives # and/or jekyll-tagging
  - jemoji