# Pretzel Settings
pretzel:
    engine: liquid

# Site Setup
title:            AnonJr.com
tagline:          '[Insert witty by-line here]'
description:      'The personal blog of AnonJr'
# imageurl:         '/public/tfr.jpg'
url:              https://blog.anonjr.com
only_frontmatter_categories: true

author:
  name:           'Mark Bussell Jr. (AnonJr)'
  url:            https://twitter.com/anonjr

# Drafts
show_drafts: false

# Disqus
# disqus_short_name:
# disqus_show_comment_count: true

# Google Analytics
google_analytics_tracking_id: UA-42177830-2

# Permalinks
#permalink:        pretty
relative_permalinks: true

permalink:        /archive/:year/:month/:day/:title/
paginate_path:    "page/:num"

paginate:         5

# Misc
exclude:
  - _misc
  - _pretzel
  - deploy.cmd
  - .gitignore
  - .git